COMPANY_NAME = 'Theriffer Inc.'
SSL_COUNTRY_NAME = 'US'
SSL_STATE_NAME = 'California'
SSL_LOCALITY_NAME = 'Pacific Palisades'
SSL_ORGANIZATIONAL_UNIT_NAME = 'Operations'
SSL_EMAIL_ADDRESS = 'theriffer@me.com'
NEW_COOKBOOK_LICENSE = :apachev2
TOPDIR = File.expand_path(File.join(File.dirname(__FILE__), '..'))
CADIR = File.expand_path(File.join(TOPDIR, 'certificates'))
